name: Deployment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t harmanxze/next-app-test:latest .
      - name: Publish image to docker hub
        run: docker push harmanxze/next-app-test:latest
      - name: Image pushed
        run: echo "Docker image pushed successfully"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy to EC2 via SSH
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo docker pull harmanxze/next-app-test:latest
            sudo docker stop next-app-test || true
            sudo docker rm next-app-test || true
            sudo docker run -d -p 3000:3000 --name next-app-test harmanxze/next-app-test:latest
          EOF
